services:
  api:
    build: .

    container_name: medical-insurance-api

    ports:
      - "8000:8000"

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CREWAI_TRACING_ENABLED=${CREWAI_TRACING_ENABLED}

    volumes:
      - uploads:/app/uploads

    networks:
      - backend

    restart: always

volumes:
  uploads:

networks:
  backend:
